package com.github.iamjosephmj.hydra

import io.ssemaj.deviceintelligence.baker.DiBaker
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.security.SecureRandom

/**
 * Generates `com.github.iamjosephmj.hydra.Hydra` into the consumer app with the
 * named secrets encrypted under a fresh per-build key.
 *
 * The key is derived in the closed baker (`DiBaker.gatedDexKey`), byte-identical
 * to the native `binding.cpp::derive_dex_key_gated` — so only the seed +
 * ciphertext land in the dex, never the key or the plaintext.
 *
 * SWEEP-GATED (DeviceIntelligence 3.2.0+): the key is bound to the unlock secret
 * U, which the native runtime publishes ONLY after the first detection sweep
 * completes clean (zero CRITICAL). At runtime `Hydra.secret(name)` hands the
 * ciphertext + seed to `StrDec.g`, which **blocks until that clean sweep** and
 * then re-derives the key. On a compromised device (root / hook / emulator /
 * clone / tamper) the sweep finds CRITICAL and the process is killed first, so
 * the secret is NEVER decrypted — no plaintext ever reaches the screen, not even
 * for a frame. Because `Hydra.secret` blocks, it MUST be called off the main
 * thread (e.g. `Dispatchers.IO`); calling it on the UI thread can ANR.
 *
 * This is the ONLY decryptor the generator emits — it is gated by construction;
 * there is no ungated path a consumer secret can reach.
 */
abstract class GenerateHydraSecretsTask : DefaultTask() {

    @get:Input
    abstract val secrets: MapProperty<String, String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val secretMap = secrets.get()
        val seed = ByteArray(32).also { SecureRandom().nextBytes(it) }
        val seedHex = toHex(seed)
        val key = DiBaker.gatedDexKey(seed)   // sweep-gated key (mixes the unlock secret U)

        val pkgDir = outputDir.get().asFile.resolve("com/github/iamjosephmj/hydra")
        pkgDir.mkdirs()

        val sb = StringBuilder()
        sb.append("package com.github.iamjosephmj.hydra;\n\n")
        sb.append("import java.util.HashMap;\n")
        sb.append("import java.util.Map;\n\n")
        sb.append("/** GENERATED by the hydra Gradle plugin. Do not edit. */\n")
        sb.append("public final class Hydra {\n")
        sb.append("    private static final String SEED = \"").append(seedHex).append("\";\n")
        sb.append("    private static final Map<String, String> S = new HashMap<>();\n")
        sb.append("    static {\n")
        for ((name, value) in secretMap) {
            sb.append("        S.put(").append(quote(name)).append(", ")
                .append(quote(encode(value, key))).append(");\n")
        }
        sb.append("    }\n\n")
        sb.append("    private Hydra() {}\n\n")
        sb.append("    /**\n")
        sb.append("     * Decrypted value of the named secret; throws if the name is unknown.\n")
        sb.append("     * SWEEP-GATED: BLOCKS until the first detection sweep completes clean,\n")
        sb.append("     * then decrypts. On a compromised device the process is killed before\n")
        sb.append("     * this returns, so the plaintext never materialises. Call OFF the main\n")
        sb.append("     * thread (e.g. Dispatchers.IO) — calling it on the UI thread can ANR.\n")
        sb.append("     */\n")
        sb.append("    public static String secret(String name) {\n")
        sb.append("        String ct = S.get(name);\n")
        sb.append("        if (ct == null) {\n")
        sb.append("            throw new IllegalArgumentException(\"hydra: unknown secret '\" + name + \"'\");\n")
        sb.append("        }\n")
        sb.append("        return io.ssemaj.deviceintelligence.internal.StrDec.g(ct, SEED);\n")
        sb.append("    }\n")
        sb.append("}\n")

        pkgDir.resolve("Hydra.java").writeText(sb.toString())
    }

    private fun toHex(b: ByteArray): String {
        val sb = StringBuilder(b.size * 2)
        for (x in b) {
            sb.append(HEX[(x.toInt() ushr 4) and 0xf])
            sb.append(HEX[x.toInt() and 0xf])
        }
        return sb.toString()
    }

    // Byte-identical to StrEncFactory.encode: hex(utf8(s)[i] XOR key[i % key.len]).
    private fun encode(s: String, key: ByteArray): String {
        val b = s.toByteArray(Charsets.UTF_8)
        val sb = StringBuilder(b.size * 2)
        for (i in b.indices) {
            val v = (b[i].toInt() and 0xff) xor (key[i % key.size].toInt() and 0xff)
            sb.append(HEX[(v ushr 4) and 0xf])
            sb.append(HEX[v and 0xf])
        }
        return sb.toString()
    }

    private fun quote(s: String): String =
        "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private companion object {
        val HEX = "0123456789abcdef".toCharArray()
    }
}
